# Generated by Django 5.1 on 2024-09-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_delivery_is_accepted_and_more'),
        ('performer', '0003_chat_is_not_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.order', verbose_name='заказ'),
        ),
    ]
