# Generated by Django 5.1 on 2024-09-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='star',
            field=models.PositiveIntegerField(default=0, verbose_name='звезда'),
        ),
    ]
