# Generated by Django 5.1 on 2024-09-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_reviews_star'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
