# Generated by Django 5.1 on 2024-09-15 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageavatar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
