# Generated by Django 5.1 on 2024-09-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'В процессе'), ('1', 'Ожидает получения'), ('1', 'Завершен')], default='1', max_length=250, verbose_name='СТАТУС'),
        ),
    ]
