# Generated by Django 5.1 on 2024-09-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_order_created_at_order_updated_at_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='принято'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='доставлено'),
        ),
    ]
