# Generated by Django 5.1 on 2024-09-07 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_additionalinformation_countryoforigin_image_service_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_navbar',
            field=models.BooleanField(default=False, verbose_name='Если выбрано, оно будет отображаться'),
        ),
        migrations.AddField(
            model_name='product',
            name='for_whom',
            field=models.CharField(choices=[(1, 'Для нее'), (2, 'Для него'), (3, 'для всех')], default=3, max_length=20, verbose_name='для кого'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активный'),
        ),
        migrations.CreateModel(
            name='SaveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
