# Generated by Django 5.1 on 2024-09-08 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_is_navbar_product_for_whom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryoforigin',
            name='product',
        ),
        migrations.RemoveField(
            model_name='typealcohol',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.countryoforigin'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_alcohol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.typealcohol'),
        ),
    ]
