# Generated by Django 5.1 on 2024-09-09 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_countryoforigin_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinformation',
            options={'verbose_name': 'Дополнительная информация', 'verbose_name_plural': 'Дополнительная информация'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренд'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='countryoforigin',
            options={'verbose_name': 'Страна происхождения', 'verbose_name_plural': 'Страна происхождения'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображение продукта'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукт'},
        ),
        migrations.AlterModelOptions(
            name='saveproduct',
            options={'verbose_name': 'Сохранить продукт', 'verbose_name_plural': 'Сохранить продукт'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'О работе сервиса', 'verbose_name_plural': 'О работе сервиса'},
        ),
        migrations.AlterModelOptions(
            name='typealcohol',
            options={'verbose_name': 'Тип Алкоголь', 'verbose_name_plural': 'Тип Алкоголь'},
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='product/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.countryoforigin', verbose_name='Страна происхождения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('$', '$'), ('€', '€'), ('£', '£'), ('¥', '¥')], default='$', max_length=20, verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='for_whom',
            field=models.CharField(choices=[('1', 'Для нее'), ('2', 'Для него'), ('3', 'для всех')], default='3', max_length=20, verbose_name='для кого'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_alcohol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.typealcohol', verbose_name='Тип Алкоголь'),
        ),
        migrations.AlterField(
            model_name='saveproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='saveproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='service',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт'),
        ),
    ]
