# Generated by Django 5.1 on 2024-09-01 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faqtwo_leavearequest_roadmap_roadmaprow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmaprow',
            name='q',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='row',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='main.roadmaprow'),
            preserve_default=False,
        ),
    ]
