# Generated by Django 5.1 on 2024-09-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_roadmaprow_q_roadmap_row'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'ВОПРОСЫ-ОТВЕТЫ', 'verbose_name_plural': 'ВОПРОСЫ-ОТВЕТЫ'},
        ),
        migrations.AlterModelOptions(
            name='faqtwo',
            options={'verbose_name': 'Часто задаваемые вопросы', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='leavearequest',
            options={'verbose_name': 'Оставьте заявку', 'verbose_name_plural': 'Оставьте заявку'},
        ),
        migrations.AlterModelOptions(
            name='roadmap',
            options={'verbose_name': 'ВОПРОСЫ-ОТВЕТЫ', 'verbose_name_plural': 'ВОПРОСЫ-ОТВЕТЫ'},
        ),
        migrations.AlterModelOptions(
            name='roadmaprow',
            options={'verbose_name': 'ВОПРОСЫ-ОТВЕТЫ', 'verbose_name_plural': 'ВОПРОСЫ-ОТВЕТЫ'},
        ),
    ]
